//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootPrints.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPositionTbl
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    }
}
